### ISSUE TITLE
worldserver doesn't start.

### ISSUE THREAD

**Issue by ddk2001** [ReyDonovan/TrinityPandaCore#1]
![image](https://github.com/ReyDonovan/TrinityPandaCore/assets/29648605/4244164c-c9ee-4440-91c4-5524872f5eb9)
worldserver doesn't start. Flashed and turned off. I quickly took a screenshot and prompted as on the picture.

**Comment by ReyDonovan** [comment]
confirm, problem mysql 8.0 need some update, or use 5.7

**Comment by ReyDonovan** [comment]
2-5 min fixed

**Comment by ReyDonovan** [comment]
![image](https://github.com/ReyDonovan/TrinityPandaCore/assets/25749510/8c09ea9e-52bd-490c-a59a-067a966d7999)

**Comment by ddk2001** [comment]
Recently I was on a business trip, and it took about 15 days, and then I tested it again. Last time I was using mysql8.0
